CD-276 multilingual webfonts
UN-OCHA/common_design pull request #253
Opened 2021-07-12 15:39 UTC by left23

I've added Chinese from the README example on this PR

Recommended on the brand portal https://brand.unocha.org/d/xEPytAUjC3sH/visual-identity#/basics/fonts-1
Chinese: Use Noto Sans CJK SC and the link to the font file download.

Currently we have `//fonts.googleapis.com/css2?family=Noto+Sans+CJK+SC:wght@400;700&display=swap` but I can't find the webfont via the Google Font UI to verify this.

I've also updated the Arabic library to load Noto Kufi and use for heading as per brand guidelines.

2021-07-16 05:47 UTC, orakili requested changes
Looks good but there are issues with Arabic and the footer in Chinese. 

I expanded on this work with theme settings to add the fonts: https://github.com/UN-OCHA/common_design/pull/255

2021-07-16 05:47 UTC, orakili commented on sass/base/_base.scss
>    font-family: $cd-font--noto;
Noto Sans doesn't handle Arabic, so that would result in the system fonts being used for Arabic.

2021-07-16 05:47 UTC, orakili commented on sass/cd/_cd-variables.scss
> +  --cd-font--noto: "Noto Sans", sans-serif;
I would argue that the variable should be named `--cd-font--noto-sans` to better reflect the real font name (smae above with `noto-kufi-arabic` and `noto-sans-sc`, notably to be more explicit and differenciate between Noto Sans and Noto Serif for example.

2021-07-16 05:47 UTC, orakili commented on sass/base/_typography.scss
> +html[lang="zh-hans"] {
in the `_cd-resets.css` it's still `lang="zh"` and it's not using the correct Chinese font I think: https://github.com/UN-OCHA/common_design/blob/5f70fdc64f4bdb34214b3ef3c667eb90691c949a/sass/cd/_cd-resets.scss#L44

2021-07-16 05:47 UTC, orakili commented on common_design.libraries.yml
> +      //fonts.googleapis.com/css2?family=Noto+Sans:wght@400;700&display=swap: { type: external, minified: true }
Noto Sans doesn't handle Arabic: https://fonts.google.com/?preview.text=%D8%A7%D9%84%D8%AD%D8%A8%20%D8%B3%D9%85%D8%A7%D8%A1%20%D9%84%D8%A7%20%D8%AA%D9%85%D8%B7%D8%B1%20%D8%BA%D9%8A%D8%B1%20%D8%A7%D9%84%D8%A3%D8%AD%D9%84%D8%A7%D9%85.&preview.text_type=custom&query=noto

2021-07-16 10:15 UTC, left23 commented
I noticed as I was setting up translation example locally that the current selectors are not adequate
```
html[lang="ar"] body {}
```
This works when the global language is set via the language switcher.
For Nodes set to specific languages, the `lang` attribute is on the article tag only.

2021-07-16 12:37 UTC, rupl commented
> `html[lang="ar"]` works when the global language is set via the language switcher.

Would it work to omit the `html` part of the selector? I often apply RTL fixes using just `[dir="rtl"]`. For example:

```css
.my-selector {
  margin-left: 1rem;
}
[dir="rtl"] .my-selector {
  margin-right: 1rem;
}
```

I'd have to setup a test page to see what happens when they nest, i.e `html[lang="en"] article[lang="ru"]`

2021-07-16 13:24 UTC, left23 commented
@rupl I'll test the nested example. I've got some local content set up already.
From what I can see, when I switch to a node whose language I've set on the node form (Arabic for example), the global language switches as well. But if I switch to another language using the global switcher, while on that node, the global language switches but the node language remains as arabic. Which is all great and what should happen. Noting it here because it takes a lot of content set up to test properly.

I expect the selector will work as you suggest. Thanks.

2021-07-16 13:53 UTC, left23 commented
@orakili Thanks, I think I've covered all your comments in the latest commits.
You mention an issue with the footer in Chinese. Can you be more specific?

2021-07-20 00:01 UTC, orakili requested changes
@left23 Thanks. I added code suggestions to change `$cd-font--noto-sc` to `$cd-font--noto-sans-sc` to be consistent with the rest, and one for a Chinese selector in`resets.scss` one chinese.

2021-07-20 08:05 UTC, orakili approved these changes

2021-07-22 08:33 UTC, merged