fix: Add an element id to the outer status messages wrapper div, so backstop can target it.
UN-OCHA/common_design pull request #472
Opened 2024-03-12 23:55 UTC by cafuego

In theory this should work, as there ought to not be another status messages wrapper.

Refs: OPS-9741

## Types of changes

-  Improvement (non-breaking change which iterates on an existing feature)
- :heavy_check_mark: Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Security update (dependency updates, or to fix a vulnerability)

## Description

Add an ID to the main wrapper for stastus messages, so we can target it for VRT using backstop, so they do not mess without screenshot diffs.

## Steps to reproduce the problem or Steps to test

  1. Run VRT as auth user.
  2. See login-link-used messages in the screenshots.
  3. Oops.

## Impact
In theory this breaks nothing and fixes something.

## PR Checklist

- [x] I have followed the Conventional Commits guidelines.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have made changes to the sub theme to reflect those in the base theme

2024-03-13 11:25 UTC, rupl requested changes
I actually have a PR open right now that would break this assumption. The OCHA AI Chat module can inject inline status messages. Is there a problem with targeting the pre-existing Drupal selector in VRT config? `[data-drupal-messages]`

2024-03-13 11:27 UTC, rupl commented
If that Drupal selector won't work, can we add a unique-enough classname instead of ID, which doesn't cause problems if it does manage to be output twice on rare occasions?

2024-03-13 21:06 UTC, cafuego commented on templates/misc/status-messages.html.twig
> +<div id="messages" data-drupal-messages>
```suggestion
<div data-drupal-messages class="messages-list">
```

2024-03-14 08:31 UTC, rupl approved these changes

2024-03-14 08:31 UTC, merged